version: '3'
services:

  db:
   image: mysql
   environment:
     MYSQL_ROOT_PASSWORD: root
   volumes:
     - C:\PRUEBA:/app:rw
   ports: 
     - 3307:3306
   container_name: coolsound
   
  app:
    depends_on:
     - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
     - '8080:80'
    environment:
      PMA_HOST: db

